### ISSUE TITLE
Problem with scanning qr codes

### ISSUE THREAD

**Issue by kcbuilder** [nilsreichardt/codemagic-app-preview#103]
## Problem

We actively using codemagic-preview-app for organizing continuous testing process, but users are experiencing difficulties in scanning the QR code generated by the Codemagic Preview app due to its low resolution (200 pixels), it getting worse when we working in extreme conditions (night mode, sunshine, etc) This issue affects usability and can hinder efficient workflow. 

## Proposed Solution: 

Implement a feature to make the QR code's resolution configurable, allowing users to adjust it based on their needs. Additionally, increase the default resolution of the QR code to ensure better scanability across various devices.

## Expected Outcome: 

By making the QR code resolution adjustable and enhancing its default quality, users will have an easier and more reliable experience when scanning QR codes, leading to improved efficiency in app development and testing processes.

**Comment by kcbuilder** [comment]
codemagic by default generating 380x380 pixels, checked their panel

**Comment by nilsreichardt** [comment]
Hey @kcrebound, thanks for the suggestion! I added a `--qr-code-size` option which allows you to set the width and height of the qr code. I also increased the default from 150 to 200.

This option is available in `v0.2.2` and above.
